# Generated by Django 6.0.5 on 2026-06-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_seed_blogposts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
    ]
